Q.No-01    Write a Python function that takes in two arrays of data and calculates the F-value for a variance ratio test. The function should return the F-value and the corresponding p-value for the test.

Ans :-

In [1]:
import scipy.stats as stats

def variance_ratio_test(data1, data2):
    n1 = len(data1)
    n2 = len(data2)
    
    variance1 = sum((x - sum(data1) / n1) ** 2 for x in data1) / (n1 - 1)
    variance2 = sum((x - sum(data2) / n2) ** 2 for x in data2) / (n2 - 1)
    
    f_value = variance1 / variance2
    degrees_of_freedom1 = n1 - 1
    degrees_of_freedom2 = n2 - 1
    
    p_value = 1 - stats.f.cdf(f_value, degrees_of_freedom1, degrees_of_freedom2)
    
    return f_value, p_value


data1 = [10, 15, 20, 25, 30]
data2 = [8, 12, 18, 24, 28]
f_value, p_value = variance_ratio_test(data1, data2)
print("F-value:", f_value)
print("p-value:", p_value)


F-value: 0.9191176470588235
p-value: 0.5315904801131142


Q.No-02    Given a significance level of 0.05 and the degrees of freedom for the numerator and denominator of an F-distribution, write a Python function that returns the critical F-value for a two-tailed test.

Ans :-

In [2]:
import scipy.stats as stats

def critical_f_value(alpha, df1, df2):
    right_critical_value = stats.f.ppf(1 - alpha / 2, df1, df2)
    left_critical_value = stats.f.ppf(alpha / 2, df1, df2)
    return left_critical_value, right_critical_value


alpha = 0.05
df1 = 3  # Degrees of freedom for the numerator
df2 = 10  # Degrees of freedom for the denominator

left_critical, right_critical = critical_f_value(alpha, df1, df2)
print(f"Critical F-values:- \n\t\tleft tail = {left_critical} \n\t\tright tail = {right_critical}")

Critical F-values:- 
		left tail = 0.06935321586551409 
		right tail = 4.825621493405406


--------------------------------------------------------------------------------------------------------------------

Q.No-03    Write a Python program that generates random samples from two normal distributions with known variances and uses an F-test to determine if the variances are equal. The program should output the Fvalue, degrees of freedom, and p-value for the test.

Ans :-

In [3]:
import numpy as np
from scipy.stats import f

# Set the seed for reproducibility
np.random.seed(42)

print("Define the parameters of the two normal distributions :-")
mean1 = 0
print(f"\n\tMean of the first distribution = {mean1}")
variance1 = 1
print(f"\tVariance of the first distribution = {variance1}")
mean2 = 0  
print(f"\tMean of the second distribution = {mean2}")
variance2 = 2
print(f"\tVariance of the second distribution = {variance2}")

print("\nGenerate random samples from the two normal distributions :-")
sample_size = 50
print(f"\n\tSample Size = {sample_size}")
sample1 = np.random.normal(mean1, np.sqrt(variance1), sample_size)
print(f"\nSamples generated First Distribution :- ")
display(sample1)
sample2 = np.random.normal(mean2, np.sqrt(variance2), sample_size)
print('Samples generated Second Distribution :- ')
display(sample2)


print("\nCalculation :-")
# Calculate the F-value, degrees of freedom, and p-value for the F-test
F_statistic = np.var(sample1, ddof=1) / np.var(sample2, ddof=1)
df1 = sample_size - 1
df2 = sample_size - 1
p_value = 1 - f.cdf(F_statistic, df1, df2)

# Print the results
print(f"\tF-value = {F_statistic}")
print(f"\tDegrees of Freedom (numerator, denominator) = {df1}, {df2}")
print(f"\tP-value = {p_value}")

# Determine whether to reject the null hypothesis (equal variances)
alpha = 0.05  # Adjust the significance level as needed

print("\nConclusion :-")
if p_value < alpha:
    print("\tReject the null hypothesis: \n\t\t\t\t\tVariances are not equal.")
else:
    print("\tFail to reject the null hypothesis: \n\t\t\t\t\tVariances are equal.")

Define the parameters of the two normal distributions :-

	Mean of the first distribution = 0
	Variance of the first distribution = 1
	Mean of the second distribution = 0
	Variance of the second distribution = 2

Generate random samples from the two normal distributions :-

	Sample Size = 50

Samples generated First Distribution :- 


array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
       -0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
       -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ,
        1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272,
        0.11092259, -1.15099358,  0.37569802, -0.60063869, -0.29169375,
       -0.60170661,  1.85227818, -0.01349722, -1.05771093,  0.82254491,
       -1.22084365,  0.2088636 , -1.95967012, -1.32818605,  0.19686124,
        0.73846658,  0.17136828, -0.11564828, -0.3011037 , -1.47852199,
       -0.71984421, -0.46063877,  1.05712223,  0.34361829, -1.76304016])

Samples generated Second Distribution :- 


array([ 0.45832394, -0.54458858, -0.95731227,  0.8650409 ,  1.45805351,
        1.31702897, -1.1868328 , -0.43729234,  0.46847724,  1.37962915,
       -0.67765471, -0.26256144, -1.56459392, -1.69169163,  1.14908504,
        1.91801304, -0.10183769,  1.41920983,  0.51143057, -0.91233711,
        0.51109057,  2.17511217, -0.05066567,  2.21274028, -3.70487906,
        1.16234567,  0.12310314, -0.42286025,  0.12976933, -2.81084692,
       -0.31066296,  0.50503344,  2.0900578 , -0.73294477, -1.14338262,
       -0.70959162,  1.29457409,  0.46492428, -0.74919406,  0.72586977,
        0.13728839,  1.36987088, -0.99285301, -0.46338425, -0.55452467,
       -2.06972269,  0.41877731,  0.36918791,  0.00723152, -0.33175631])


Calculation :-
	F-value = 0.5701772691968628
	Degrees of Freedom (numerator, denominator) = 49, 49
	P-value = 0.9740369803378406

Conclusion :-
	Fail to reject the null hypothesis: 
					Variances are equal.


--------------------------------------------------------------------------------------------------------------------

Q.No-04    The variances of two populations are known to be 10 and 15. A sample of 12 observations is taken from each population. Conduct an F-test at the 5% significance level to determine if the variances are significantly different.

Ans :-

In [4]:
import numpy as np
from scipy.stats import f_oneway

print("Given :-")
# Given variances
variance1 = 10
print(f"\tVariance of Frist Populations = {variance1}")
variance2 = 15
print(f"\tVariance of Second Population = {variance2}")
# Sample sizes
n1 = 12
print(f"\tSample Size of Frist Populations = {n1}")
n2 = 12
print(f"\tSample Size of Second Population = {n2}")

print("\nGenerate random samples from the populations (you can replace this with your actual data) :-")
population1 = np.random.normal(0, np.sqrt(variance1), n1)
print("\nFirst Population Data :-")
display(population1)
population2 = np.random.normal(0, np.sqrt(variance2), n2)
print("Second Population Data :- ")
display(population2)

print("Performing One-Way ANOVA Test :-")
# Perform the F-test
_, p_value = f_oneway(population1, population2)
print(f"\tP-Value = {p_value}")

# Set significance level
alpha = 0.05
print(f"\tSignificance Level = {alpha}")

print("\nConclusion :-")
# Compare the p-value to the significance level
if p_value < alpha:
    print("\tReject the null hypothesis: \n\t\t\t\t\tThe variances are significantly different.")
else:
    print("\tFail to reject the null hypothesis: \n\t\t\t\t\tThe variances are not significantly different.")

Given :-
	Variance of Frist Populations = 10
	Variance of Second Population = 15
	Sample Size of Frist Populations = 12
	Sample Size of Second Population = 12

Generate random samples from the populations (you can replace this with your actual data) :-

First Population Data :-


array([-4.47579528, -1.33019731, -1.08375846, -2.53702349, -0.5100302 ,
        1.277721  ,  5.96464354,  0.55206352,  0.81444585, -0.23541866,
       -6.06768735, -0.08384424])

Second Population Data :- 


array([ 0.2332706 ,  9.54009568, -0.74501081,  1.16788783, -0.13443811,
       -4.52627058,  4.42613373,  2.91222411,  3.06365356, -3.52204247,
        5.432999  , -5.42934582])

Performing One-Way ANOVA Test :-
	P-Value = 0.28486807431129235
	Significance Level = 0.05

Conclusion :-
	Fail to reject the null hypothesis: 
					The variances are not significantly different.


--------------------------------------------------------------------------------------------------------------------

Q.No-05    A manufacturer claims that the variance of the diameter of a certain product is 0.005. A sample of 25 products is taken, and the sample variance is found to be 0.006. Conduct an F-test at the 1% significance level to determine if the claim is justified.

Ans :-

In [5]:
import scipy.stats as stats

print("Given Data :-")
sample_variance = 0.006
print(f"\tSample variance = {sample_variance}")
claimed_variance = 0.005
print(f"\tClaimed Variance = {claimed_variance}")
sample_size = 25
print(f"\tNumber of Product (Sample Size) = {sample_size}")

print("\nCalculation :-")
# Calculate the F-statistic
F_statistic = sample_variance / claimed_variance
print(f"\tF Statistic = {F_statistic} ")

# Calculate degrees of freedom
df1 = sample_size - 1
print(f"\tDegrees of Freedom for numerator = {df1}")
df2 = sample_size - 1
print(f"\tDegrees of Freedom for denominator = {df2}")

# Calculate the p-value
p_value = 2 * (1 - stats.f.cdf(F_statistic, df1, df2))
print(f"\tp value = {p_value}")

# Set the significance level
alpha = 0.01
print(f"\nSignificance Level = {alpha}")

print("\nConclusion :-")
# Determine if the null hypothesis should be rejected
if p_value < alpha:
    print("\tReject the null hypothesis. \n\t\t\t\t\tThe claimed variance is not justified.")
else:
    print("\tFail to reject the null hypothesis. \n\t\t\t\t\tThe claimed variance is justified.")


Given Data :-
	Sample variance = 0.006
	Claimed Variance = 0.005
	Number of Product (Sample Size) = 25

Calculation :-
	F Statistic = 1.2 
	Degrees of Freedom for numerator = 24
	Degrees of Freedom for denominator = 24
	p value = 0.6587309365634488

Significance Level = 0.01

Conclusion :-
	Fail to reject the null hypothesis. 
					The claimed variance is justified.


--------------------------------------------------------------------------------------------------------------------

Q.No-06    Write a Python function that takes in the degrees of freedom for the numerator and denominator of an F-distribution and calculates the mean and variance of the distribution. The function should return the mean and variance as a tuple.

Ans :-

In [6]:
def calculate_f_distribution_mean_variance(df1, df2):
    if df2 <= 2:
        raise ValueError("The denominator degrees of freedom (df2) must be greater than 2.")
    
    mean = df2 / (df2 - 2)
    variance = (2 * (df2 ** 2) * (df1 + df2 - 2)) / (df1 * ((df2 - 2) ** 2) * (df2 - 4))
    
    return mean, variance


df1 = 5
print(f"Degrees of freedom for the numerator = {df1}")
df2 = 10
print(f"Degrees of freedom for the denominator = {df2}")

mean, variance = calculate_f_distribution_mean_variance(df1, df2)
print(f"Mean: {mean}")
print(f"Variance: {variance}")

Degrees of freedom for the numerator = 5
Degrees of freedom for the denominator = 10
Mean: 1.25
Variance: 1.3541666666666667


--------------------------------------------------------------------------------------------------------------------

Q.No-07    A random sample of 10 measurements is taken from a normal population with unknown variance. The sample variance is found to be 25. Another random sample of 15 measurements is taken from another normal population with unknown variance, and the sample variance is found to be 20. Conduct an F-test at the 10% significance level to determine if the variances are significantly different.

Ans :-

In [7]:
import scipy.stats as stats

print("Given Data :-")
# Sample variances
variance_sample1 = 25
print(f"\tVariance Sample 01 = {variance_sample1}")
sample_size1 = 10
print(f"\tSample Size of Sample 01 = {sample_size1}")
variance_sample2 = 20
print(f"\tVariance Sample 02 = {variance_sample2}")
sample_size2 = 15
print(f"\tSample Size of Sample 02 = {sample_size2}")


print("\nCalculation :-")
# Degrees of freedom for the two samples
df1 = 10 - 1
print("\tDegrees Of Freedom For Sample 01: ", df1)
df2 = 15 - 1
print("\tDegrees Of Freedom For Sample 02: ", df2, "\n\n")

# Calculate the F-statistic
F_statistic = variance_sample1 / variance_sample2
print(f"\tThe value of f statistic = {F_statistic}")

# Define the significance level
alpha = 0.10
print(f"\tSignificance Level = {alpha}")

# Calculate the critical value for the F-test
critical_value = stats.f.ppf(1 - alpha / 2, df1, df2)
print(f"\tCritical Value at Significance Level ({round((1-(alpha/2))*100)}%) = {critical_value} ")

print("\nConclusion :-")
# Compare the F-statistic to the critical value
if F_statistic < 1 / critical_value or F_statistic > critical_value:
    print("\tReject the null hypothesis: \n\t\t\t\t\tVariances are significantly different")
else:
    print("\tFail to reject the null hypothesis: \n\t\t\t\t\tVariances are not significantly different")


Given Data :-
	Variance Sample 01 = 25
	Sample Size of Sample 01 = 10
	Variance Sample 02 = 20
	Sample Size of Sample 02 = 15

Calculation :-
	Degrees Of Freedom For Sample 01:  9
	Degrees Of Freedom For Sample 02:  14 


	The value of f statistic = 1.25
	Significance Level = 0.1
	Critical Value at Significance Level (95%) = 2.6457907352338195 

Conclusion :-
	Fail to reject the null hypothesis: 
					Variances are not significantly different


--------------------------------------------------------------------------------------------------------------------

Q.No-09    The following data represent the waiting times in minutes at two different restaurants on a Saturday night: Restaurant A: 24, 25, 28, 23, 22, 20, 27; Restaurant B: 31, 33, 35, 30, 32, 36. Conduct an F-test at the 5% significance level to determine if the variances are significantly different.

Ans :-

In [8]:
import numpy as np
from scipy.stats import f_oneway

print("Given Data :-")
# Data for Restaurant A and Restaurant B
restaurant_A = np.array([24, 25, 28, 23, 22, 20, 27])
print("\nWaiting times in munutes on a Saturday Night at Restaurant A :")
display(restaurant_A)
restaurant_B = np.array([31, 33, 35, 30, 32, 36])
print("Waiting times in minutes on a Saturday Night at Restaurant B :")
display(restaurant_B)
alpha = 0.05
print(f"Significance Level = {alpha}")


print("\nCalculation :-")
ddof = 1
print(f"\tDegree Of Freedom for unbiased sample variance = {ddof}")

# Calculate the variances
variance_A = np.var(restaurant_A, ddof=ddof)
print(f"\tVariance for Restaurant A = {variance_A}")
variance_B = np.var(restaurant_B, ddof=ddof)
print(f"\tVariance for Restaurant B = {variance_B}")

# Perform an F-test (ANOVA)
f_statistic, p_value = f_oneway(restaurant_A, restaurant_B)
print(f"\tF Statisticof ANOVA test = {f_statistic}")
print(f"\tP Value of ANOVA test = {p_value}")

print("\nConclusion :-")
# Check if the variances are significantly different
if p_value < alpha:
    print("\tThe variances are significantly different at the {}% significance level.".format(100*(1-alpha)))
else:
    print("\tThere is no significant difference in variances at the {}% significance level.".format(100*(1-alpha)))


Given Data :-

Waiting times in munutes on a Saturday Night at Restaurant A :


array([24, 25, 28, 23, 22, 20, 27])

Waiting times in minutes on a Saturday Night at Restaurant B :


array([31, 33, 35, 30, 32, 36])

Significance Level = 0.05

Calculation :-
	Degree Of Freedom for unbiased sample variance = 1
	Variance for Restaurant A = 7.80952380952381
	Variance for Restaurant B = 5.366666666666667
	F Statisticof ANOVA test = 36.42289051820553
	P Value of ANOVA test = 8.487593714710292e-05

Conclusion :-
	The variances are significantly different at the 95.0% significance level.


--------------------------------------------------------------------------------------------------------------------

Q.No-09    The following data represent the test scores of two groups of students: Group A: 80, 85, 90, 92, 87, 83; Group B: 75, 78, 82, 79, 81, 84. Conduct an F-test at the 1% significance level to determine if the variances are significantly different.

Ans :-

In [13]:
import numpy as np
from scipy.stats import f

print("Given Data :-")
# Define the data for Group A and Group B
group_a = np.array([80, 85, 90, 92, 87, 83])
print(f"\nFrist Group fo Student :")
display(group_a)
group_b = np.array([75, 78, 82, 79, 81, 84])
print("Second group of student :")
display(group_b)

print("Calculation :-")
ddof = 1
print(f"\tDegree Of Freedom for sample variance = {ddof}")
# Calculate the variances for each group
variance_a = np.var(group_a, ddof=ddof)
print(f"\tVariances for Group A = {variance_a}")  
variance_b = np.var(group_b, ddof=ddof)
print(f"\tVariances for Group B = {variance_b}\n\n")

# Calculate the F-statistic
f_statistic = variance_a / variance_b
print(f"\tF-Statistic = {f_statistic}")

# Define the degrees of freedom for each group
df_a = len(group_a) - 1
print(f"\tDefine the degrees of freedom for Group A = {df_a}")
df_b = len(group_b) - 1
print(f"\tDefine the degrees of freedom for Group B = {df_b}")

# Calculate the p-value for the F-statistic
p_value = 1 - f.cdf(f_statistic, df_a, df_b)
print(f"\tP Value = {p_value}")

# Set the significance level
alpha = 0.01
print(f"\nSignificance Level = {alpha}")


print("\nConclusion :-")
# Determine if the variances are significantly different
if p_value < alpha:
    print("\tReject the null hypothesis. \n\t\t\t\t\tVariances are significantly different.")
else:
    print("\tFail to reject the null hypothesis. \n\t\t\t\t\tVariances are not significantly different.")


Given Data :-

Frist Group fo Student :


array([80, 85, 90, 92, 87, 83])

Second group of student :


array([75, 78, 82, 79, 81, 84])

Calculation :-
	Degree Of Freedom for sample variance = 1
	Variances for Group A = 19.76666666666667
	Variances for Group B = 10.166666666666666


	F-Statistic = 1.9442622950819677
	Define the degrees of freedom for Group A = 5
	Define the degrees of freedom for Group B = 5
	P Value = 0.2415521774535344

Significance Level = 0.01

Conclusion :-
	Fail to reject the null hypothesis. 
					Variances are not significantly different.


                                        END